"""create scenarios table

Revision ID: 71364e489d38
Revises: 
Create Date: 2026-05-17 00:15:23.203484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71364e489d38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('plant_name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('annualGeneration', sa.Float(), nullable=True),
    sa.Column('heatInput', sa.Float(), nullable=True),
    sa.Column('SO2Rate', sa.Float(), nullable=True),
    sa.Column('operatingHours', sa.Float(), nullable=True),
    sa.Column('baselineSO2', sa.Float(), nullable=True),
    sa.Column('baselineNOx', sa.Float(), nullable=True),
    sa.Column('baselinePM25', sa.Float(), nullable=True),
    sa.Column('baselineVOC', sa.Float(), nullable=True),
    sa.Column('baselineCO2', sa.Float(), nullable=True),
    sa.Column('bau_totalBenefit', sa.Float(), nullable=True),
    sa.Column('bau_totalAnnualCost', sa.Float(), nullable=True),
    sa.Column('bau_netBenefit', sa.Float(), nullable=True),
    sa.Column('gt_totalBenefit', sa.Float(), nullable=True),
    sa.Column('gt_totalAnnualCost', sa.Float(), nullable=True),
    sa.Column('gt_netBenefit', sa.Float(), nullable=True),
    sa.Column('rt_totalBenefit', sa.Float(), nullable=True),
    sa.Column('rt_totalAnnualCost', sa.Float(), nullable=True),
    sa.Column('rt_netBenefit', sa.Float(), nullable=True),
    sa.Column('ac_totalBenefit', sa.Float(), nullable=True),
    sa.Column('ac_totalAnnualCost', sa.Float(), nullable=True),
    sa.Column('ac_netBenefit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
